site_name: MIT AlphaPilot
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - shell
        - python

site_author: MIT
copyright: "MIT 2019"
markdown_extensions:
- admonition
- attr_list
- pymdownx.arithmatex
#- toc
#    baselevel: 4

# https://github.com/mkdocs/mkdocs/issues/1678
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#arithmatex-mathjax
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
